# .goreleaser.yaml
project_name: borgmatic-exporter
builds:
  -
    id: borgmatic-exporter
    main: ./cmd/borgmatic-exporter
    goos:
      - darwin
      - linux
      - netbsd
      - freebsd
      - openbsd
    goarch:
      - '386'
      - amd64
      - arm64
      - arm
      - mips
      - mipsle
      - mips64le
      - ppc64le
      - s390x
    
